### ISSUE TITLE
Graph "Questions completion": green as default color for closing commit

### ISSUE THREAD

**Issue by raclet** [git4school/git4school-visu#5]
Graph "Questions completion": a closing commit should appear in green when the question solved by the closing commit is not referenced in any review.

**Comment by F0urchette** [comment]
If there is no review or correction associated to a commit that completes a question (closing commit), we now want it to be **green in every graphs**
- Here is a summary table for the color assignment of a closing commit :

![tableau](https://user-images.githubusercontent.com/16985364/98880539-45322b00-2488-11eb-9969-12b5587c8680.png)
